--- #YAML:1.0
name:               TAIR-GeneDescriptions
version:            1.00
abstract:           Automatically download gene descriptions using locus identifiers (AGI codes) or gene names.
author:
    - Haktan Suren <hsuren@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request::Common:  0
    LWP::UserAgent:       0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
